FROM python:3.8.13

# 1. Copy the requirements.txt file to the image
COPY ./requirements.txt /src/requirements.txt

WORKDIR /src

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY ./ /src/
CMD python /src/populate_db.py
